routes/web.php
<?php

use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function () {
    return view('home');
})->name('home')->middleware('auth');

Route::resource('users',UserController::class);
Route::resource('projects',ProjectController::class);
Route::resource('reports',ReportController::class);

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;
    protected $table = 'projects';

    protected $fillable = [
        'project_name',
        'detail',
        'duration_from',
        'duration_to',
        'revenue',
    ];
    public function work()
    {
        return $this->hasMany('App\Models\Work');
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;
use DataTables;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Project::latest()->get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $btn = '<a
                    href="javascript:void(0)"
                    data-toggle="tooltip"
                    data-id="' . $row->id . '"
                    data-original-title="Edit"
                    class="edit btn btn-primary btn-sm editProject">
                        Edit
                    </a>';
                    $btn .=' <a
                    href="javascript:void(0)"
                    data-toggle="tooltip"
                    data-id="' . $row->id . '
                    " data-original-title="Delete"
                    class="btn btn-danger btn-sm deleteProject">
                    Delete
                    </a>';

                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('admin.project.list');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Project::updateOrCreate(['id' => $request->id],
            [
                'project_name' => $request->project_name,
                'detail' => $request->detail,
                'password' => $request->password,
                'duration_from' => $request->duration_from,
                'duration_to' => $request->duration_to,
                'revenue' => $request->revenue
            ]
        );

        return response()->json(['success' => 'Project saved successfully.']);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = Project::find($id);

        return response()->json($project);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Project::find($id)->delete();

        return response()->json(['success' => 'Project deleted successfully.']);
    }
}

resources/views/admin/project/list.blade.php
@extends('adminlte::page')
@section('content')
    <body>
    <div class="container mt-5">
        <h2 class="mb-4">List Project</h2>
        <div class="col-md-12 text-right mb-5">
            <a class="btn btn-success" href="javascript:void(0)" id="create-project"> Create New Project</a>
        </div>
        <table class="table table-bordered project-table">
            <thead>
            <tr>
                <th>No</th>
                <th>Project Name</th>
                <th>Detail</th>
                <th>Duration from</th>
                <th>Duration to</th>
                <th>Revenue</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <!-- Show form add/edit Project  -->
    <div class="modal fade" id="projectModel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modelHeading"></h4>
                </div>
                <div class="modal-body">
                    <form id="projectForm" name="projectForm" class="form-horizontal">
                        <input type="hidden" name="id" id="id">
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="project_name" name="project_name"
                                       placeholder="Enter project name" required="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">Detail</label>
                            <div class="col-sm-12">
                                <textarea type="text" class="form-control" id="detail" name="detail"
                                          placeholder="Enter detail project..." rows="2" required=""></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">Duration from</label>
                            <div class="col-sm-12">
                                <input type="date" id="duration_from" name="duration_from"
                                       class="form-control" placeholder="Birthday">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">Duration to</label>
                            <div class="col-sm-12">
                                <input type="date" id="duration_to" name="duration_to"
                                       class="form-control" placeholder="Birthday">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">Revenue</label>
                            <div class="col-sm-12">
                                <input type="number" class="form-control" id="revenue" name="revenue"
                                       placeholder="Enter revenue($USD)" required="">
                            </div>
                        </div>
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary" id="saveProject" value="create">Save changes
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- End show form add/edit project -->
    </body>
@endsection
@section('js')
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('.project-table').DataTable({
                "bDestroy": true,
                processing: true,
                serverSide: true,
                ajax: "{{ route('projects.index') }}",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'project_name', name: 'project_name'},
                    {data: 'detail', name: 'detail'},
                    {data: 'duration_from', name: 'duration_from'},
                    {data: 'duration_to', name: 'duration_to'},
                    {data: 'revenue', name: 'revenue'},
                    {
                        data: 'action',
                        name: 'action',
                        orderable: true,
                        searchable: true
                    },
                ]
            });
        });

        $('#create-project').click(function () {
            $('#saveProject').val("create-project");
            $('#id').val('');
            $('#projectForm').trigger("reset");
            $('#modelHeading').html("Create New Project");
            $('#projectModel').modal('show');
        });

        $('body').on('click', '.editProject', function () {
            var id = $(this).data('id');
            $.get("{{ route('projects.index') }}" + '/' + id + '/edit', function (data) {
                $('#modelHeading').html("Edit Project");
                $('#saveProject').val("edit-user");
                $('#projectModel').modal('show');
                $('#id').val(data.id);
                $('#project_name').val(data.project_name);
                $('#detail').val(data.detail);
                $('#duration_from').val(data.duration_from);
                $('#duration_to').val(data.duration_to);
                $('#revenue').val(data.revenue);
            })
        });

        $('#saveProject').click(function (e) {
            e.preventDefault();
            $(this).html('Sending..');

            $.ajax({
                data: $('#projectForm').serialize(),
                url: "{{ route('projects.store') }}",
                type: "POST",
                dataType: 'json',
                success: function (data) {
                    $('#projectForm').trigger("reset");
                    $('#projectModel').modal('hide');
                    location.reload();
                    table.draw();
                },
                error: function (data) {
                    console.log('Error:', data);
                    $('#saveProject').html('Save Changes');
                }
            });
        });
        $('body').on('click', '.deleteProject', function () {
            const id = $(this).data("id");
            const result = confirm("Are You sure want to delete project !");
            if (result) {
                $.ajax({
                    type: "DELETE",
                    url: "{{ route('projects.store') }}" + '/' + id,
                    success: function (data) {
                        location.reload();
                        table.draw();
                    },
                    error: function (data) {
                        console.log('Error:', data);
                    }
                });
            } else {
                return false;
            }
        });

    </script>


@endsection