routes/web.php
<?php

use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function () {
    return view('home');
})->name('home')->middleware('auth');

Route::resource('users',UserController::class);
Route::resource('projects',ProjectController::class);
Route::resource('reports',ReportController::class);

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Models\Work;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\DataTables;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     * @throws \Exception
     */
    public function index(Request $request)
    {
        $projects_name= DB::table('projects')->select('project_name')->get();
        if ($request->ajax()) {
            $data = DB::table('work_project')
                ->select(
                    'work_project.id',
                    'role',
                    'user_id',
                    'project_id',
                    'working_time',
                    'working_type',
                    'work_project.detail as work_detail',
                    'project_name',
                    'work_project.created_at as report_date',
                    'users.name as user_name'
                )
                ->join('users', 'work_project.user_id', '=', 'users.id')
                ->join('projects', 'work_project.project_id', '=', 'projects.id')
//                ->where('user_id',Auth::user()->id)
                ->get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row)
                {
                    $btn = '<a
                    href="javascript:void(0)"
                    data-toggle="tooltip"
                    data-id="' . $row->id . '
                    " data-original-title="Edit"
                    class="edit btn btn-primary btn-sm editReport">
                    Edit
                    </a>';
                    $btn .= ' <a
                    href="javascript:void(0)"
                    data-toggle="tooltip"
                    data-id="' . $row->id . '
                    " data-original-title="Delete"
                    class="btn btn-danger btn-sm deleteReport">
                    Delete
                    </a>';

                    return $btn;
                }
                )
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('admin.report.report_user',compact('projects_name'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request): \Illuminate\Http\JsonResponse
    {
        $time = Carbon::now ('Asia/Ho_Chi_Minh');
        $user_id = Auth::id();
        $project_id = DB::table('projects')->where('project_name',"Project 4")->first()->id;
        Work::updateOrCreate(['id' => $request->id],
            [
                'user_id'=>$user_id,
                'project_id' => $project_id,
                'role' => $request->role,
                'working_time' => $request->working_hour,
                'working_type' => $request->working_type,
                'detail' => $request->work_detail,
                'created_at'=>$time->toDateString(),
                'updated_at'=>$time->toDateString(),
            ]
        );

        return response()->json(['success' => 'Report saved successfully.']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function edit($id)
    {
        $data = DB::table('work_project')
            ->select(
                'work_project.id as work_id',
                'work_project.id',
                'role',
                'user_id',
                'project_id',
                'working_time',
                'working_type',
                'work_project.detail as work_detail',
                'project_name',
            )
            ->join('users', 'work_project.user_id', '=', 'users.id')
            ->join('projects', 'work_project.project_id', '=', 'projects.id')
            ->where('work_project.id',$id)
            ->get();

        return response()->json($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        Work::find($id)->delete();

        return response()->json(['success' => 'User deleted successfully.']);
    }
}

resources/views/admin/report/report_user.blade.php
@extends('adminlte::page')
@section('content')


    <body>
    <div class="container mt-5">
        <h2 class="mb-4">All report</h2>
        <div class="col-md-12 text-right mb-5">
            <a class="btn btn-success" href="javascript:void(0)" id="createNewReport"> Create New Report</a>
        </div>
        <table class="table table-bordered tableReport">
            <thead>
            <tr>
                <th>No</th>
                <th>Project ID</th>
                <th>User ID</th>
                <th>Role</th>
                <th>Working hour</th>
                <th>Work Type</th>
                <th>Detail</th>
                <th>Report Date</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
        <div class="modal fade" id="create-update-report" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="modelHeading"></h4>
                    </div>
                    <div class="modal-body">
                        <form id="reportForm" name="reportForm" class="form-horizontal">
                            <input type="hidden" name="id" id="id">
                            <div clas="form-group">
                                <div class="col-sm-12">
                                    <x-adminlte-select id="project_name" name="project_name" label="Project Name" label-class="text-lightblue"
                                                       igroup-size="lg">
                                        <x-slot name="prependSlot">
                                            <div class="input-group-text bg-gradient-info">
                                                <i class="fas fa-user-alt"></i>
                                            </div>
                                        </x-slot>
                                        <option></option>
                                        @foreach($projects_name as $key)
                                        <option>{{$key->project_name}}</option>
                                        @endforeach
                                        <optin>Other</optin>
                                    </x-adminlte-select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <x-adminlte-select name="role" label="Role" label-class="text-lightblue"
                                                       igroup-size="lg">
                                        <x-slot name="prependSlot">
                                            <div class="input-group-text bg-gradient-info">
                                                <i class="fas fa-user-alt"></i>
                                            </div>
                                        </x-slot>
                                        <option></option>
                                        <option>Developer</option>
                                        <option>Tester</option>
                                        <option>Comtor</option>
                                        <option>Brse</option>
                                        <option>PM</option>
                                        <option>Other</option>
                                    </x-adminlte-select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <x-adminlte-select id="working_type" name="working_type" label="Working type" label-class="text-lightblue"
                                                       igroup-size="lg">
                                        <x-slot name="prependSlot">
                                            <div class="input-group-text bg-gradient-info">
                                                <i class="fas fa-user-alt"></i>
                                            </div>
                                        </x-slot>
                                        <option></option>
                                        <option>remote</option>
                                        <option>offsite</option>
                                        <option>onsite</option>
                                        <option>off</option>

                                    </x-adminlte-select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label text-lightblue">Working hours</label>
                                <div class="col-sm-12">
                                    <input type="number" class="form-control" id="working_hour" name="working_hour"
                                           placeholder="Enter the number of working hours" value="" required="">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label text-lightblue">Detail</label>
                                <div class="col-sm-12">
                                    <textarea type="text" class="form-control" id="work_detail" name="work_detail" value="" rows="2" placeholder="Job summary here"></textarea>
                                </div>
                            </div>

                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary" id="saveReport" value="create">Save changes
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </body>

    @endsection
    @section('js')

        <script type="text/javascript">
            $(function () {

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                var table = $('.tableReport').DataTable({
                    "bDestroy": true,
                    processing: true,
                    serverSide: true,
                    ajax: "{{ route('reports.index') }}",
                    columns: [
                        {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                        {data: 'project_name', name: 'project_name'},
                        {data: 'user_name', name: 'user_name'},
                        {data: 'role', name: 'role'},
                        {data: 'working_time', name: 'working_time'},
                        {data: 'working_type', name: 'working_type'},
                        {data: 'work_detail', name: 'work_detail'},
                        {data: 'report_date', name: 'report_date'},
                        {
                            data: 'action',
                            name: 'action',
                            orderable: true,
                            searchable: true
                        },
                    ]
                });

            });
            $('#createNewReport').click(function () {
                $('#saveReport').val("create-report");
                $('#id').val('');
                $('#reportForm').trigger("reset");
                $('#modelHeading').html("Create New Report");
                $('#create-update-report').modal('show');
            });

            $('body').on('click', '.editReport', function () {
                var id = $(this).data('id');
                $.get("{{ route('reports.index') }}" + '/' + id + '/edit', function (data) {
                    $('#modelHeading').html("Edit Report");
                    $('#saveReport').val("edit-report");
                    $('#create-update-report').modal('show');
                    $('#id').val(data.id);
                    $('#project_name').val(data[0].project_name);
                    $('#role').val(data[0].role);
                    $('#working_type').val(data[0].working_type);
                    $('#working_hour').val(data[0].working_time);
                    $('#work_detail').val(data[0].work_detail);
                })
            });

            $('#saveReport').click(function (e) {
                e.preventDefault();
                $(this).html('Sending..');

                $.ajax({
                    data: $('#reportForm').serialize(),
                    url: "{{ route('reports.store') }}",
                    type: "POST",
                    dataType: 'json',
                    success: function (data) {
                        $('#reportForm').trigger("reset");
                        $('#create-update-report').modal('hide');
                        location.reload();
                        table.draw();
                    },
                    error: function (data) {
                        console.log('Error:', data);
                        $('#saveReport').html('Save Changes');
                    }
                });
            });
            $('body').on('click', '.deleteReport', function () {
                var id = $(this).data("id");
                var result = confirm("Are You sure want to delete Report !");
                if (result) {
                    $.ajax({
                        type: "DELETE",
                        url: "{{ route('reports.store') }}" + '/' + id,
                        success: function (data) {
                            location.reload();
                            table.draw();
                        },
                        error: function (data) {
                            console.log('Error:', data);
                        }
                    });
                } else {
                    return false;
                }
            });
        </script>
@endsection